### PR TITLE
Add "DIVERS" to anrede enum

### PR DESCRIPTION
**Pull request by hf-kklein**

### CODE REVIEW

**Review by hf-krechan — APPROVED** [review]

**Comment by hf-kklein** [comment]
this was thought to be an example for demonstrating the git workflow ;)

**Comment by hf-krechan** [comment]
Which got workflow? ^^

**Comment by hf-fvesely** [comment]
🤿

**Comment by hf-kklein** [comment]
we can re-open that later. as i said it was mainly for demo purposes

**Pull request closed without merging**
